# Generated by Django 5.0.7 on 2024-09-29 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentmodel',
            name='react',
        ),
    ]
