# Generated by Django 5.0.7 on 2024-07-27 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='content_model',
            new_name='content',
        ),
    ]
