# Generated by Django 5.0.7 on 2024-07-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='reaction',
            new_name='reaction_type',
        ),
    ]
