# Generated by Django 5.0.7 on 2024-07-27 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_reaction_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.contentmodel'),
        ),
    ]
