# Generated by Django 5.0.7 on 2024-07-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_post_id_alter_blog_react'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='posts',
        ),
    ]
